AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys a basic stuff to get the aws account set up'
Parameters:
  LambdaName:
    Type: String
    Description: Name of Lambda Function
  S3ArtifactStore:
    Type: String
    Description: Name of S3 bucket

Resources:
  
  # Lambda
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Code: ./
      Handler: lambda.handler
      Runtime: python3.9
      Role: arn:aws:lambda:ap-south-1:179750807597:function:lam-integration-test
      PackageType: Zip
